
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main.cup;

/** CUP generated class containing symbol constants. */
public class VCParserSym {
  /* terminals */
  public static final int DIVIDE = 17;
  public static final int BOOLEANLITERAL = 39;
  public static final int COMMENT = 36;
  public static final int SUBTRACT = 15;
  public static final int SEMI = 29;
  public static final int CONTINUE = 4;
  public static final int INT = 9;
  public static final int ARRAY = 41;
  public static final int LESS = 18;
  public static final int FOR = 6;
  public static final int FLOATLITERAL = 38;
  public static final int NOT = 27;
  public static final int AND = 26;
  public static final int LTRIBRACE = 34;
  public static final int OR = 25;
  public static final int COMMA = 28;
  public static final int MOREEQ = 21;
  public static final int PLUS = 14;
  public static final int MULTIPLY = 16;
  public static final int LESSEQ = 19;
  public static final int IF = 8;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 10;
  public static final int error = 1;
  public static final int INTEGERLITERAL = 37;
  public static final int EQEQ = 23;
  public static final int BREAK = 3;
  public static final int VOID = 11;
  public static final int EQ = 22;
  public static final int LBRACK = 32;
  public static final int LBRACE = 30;
  public static final int ELSE = 5;
  public static final int RBRACK = 33;
  public static final int WHILE = 12;
  public static final int FLOAT = 7;
  public static final int RBRACE = 31;
  public static final int STRINGLITERAL = 40;
  public static final int RTRIBRACE = 35;
  public static final int MORE = 20;
  public static final int NOTEQ = 24;
  public static final int IDENTIFIER = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "KEYWORD.BOOLEAN",
  "KEYWORD.BREAK",
  "KEYWORD.CONTINUE",
  "KEYWORD.ELSE",
  "KEYWORD.FOR",
  "KEYWORD.FLOAT",
  "KEYWORD.IF",
  "KEYWORD.INT",
  "KEYWORD.RETURN",
  "KEYWORD.VOID",
  "KEYWORD.WHILE",
  "IDENTIFIER",
  "OPERATORS.PLUS",
  "OPERATORS.SUBTRACT",
  "OPERATORS.MULTIPLY",
  "OPERATORS.DIVIDE",
  "OPERATORS.LESS",
  "OPERATORS.LESSEQ",
  "OPERATORS.MORE",
  "OPERATORS.MOREEQ",
  "OPERATORS.EQ",
  "OPERATORS.EQEQ",
  "OPERATORS.NOTEQ",
  "OPERATORS.OR",
  "OPERATORS.AND",
  "OPERATORS.NOT",
  "SEPARATOR.COMMA",
  "SEPARATOR.SEMI",
  "SEPARATOR.LBRACE",
  "SEPARATOR.RBRACE",
  "SEPARATOR.LBRACK",
  "SEPARATOR.RBRACK",
  "SEPARATOR.LTRIBRACE",
  "SEPARATOR.RTRIBRACE",
  "COMMENT",
  "LITERAL.INTEGERLITERAL",
  "LITERAL.FLOATLITERAL",
  "LITERAL.BOOLEANLITERAL",
  "LITERAL.STRINGLITERAL",
  "ARRAY"
  };
}

